# Generated by Django 4.0.4 on 2022-07-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0005_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detalle',
            field=models.CharField(default='Haga click para leer más.', max_length=255),
        ),
    ]
