# Generated by Django 4.0.4 on 2022-07-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0006_post_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='detalle',
            field=models.CharField(max_length=255),
        ),
    ]
