# Generated by Django 4.0.4 on 2022-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0007_post_header_img_alter_post_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, default='profile_img/925667.jpg', null=True, upload_to='imagenes/'),
        ),
    ]
